### ISSUE TITLE
Error when try to start miner.

### ISSUE THREAD

**Issue by kirush0280** [qpwedev/gramcoin-miner#1]
```
$ npx ts-node main.ts 
/home/alex/ton-build/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at attemptRequireWithV8CompileCache (/home/alex/ton-build/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.10_typescript@5.3.3/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/home/alex/ton-build/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.10_typescript@5.3.3/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/home/alex/ton-build/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.10_typescript@5.3.3/node_modules/ts-node/dist/configuration.js:226:16)
```
$ uname -a
Linux alex-H81M-DS2 5.15.0-82-generic #91~20.04.1-Ubuntu SMP Fri Aug 18 16:24:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kirush0280** [comment]
First problem was resolved by update npm. But second I cant resolve :(
when try to send message in smart contract:
```
[Sending transaction]
/home/alex/ton-build/node_modules/.pnpm/axios@0.25.0/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 500
    at createError (/home/alex/ton-build/node_modules/.pnpm/axios@0.25.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/alex/ton-build/node_modules/.pnpm/axios@0.25.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/alex/ton-build/node_modules/.pnpm/axios@0.25.0/node_modules/axios/lib/adapters/http.js:312:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
......


    data: {
      ok: false,
      error: 'LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\n' +
        'Cannot run message on account: inbound external message rejected by transaction DD20A085191BBBF20D40B28938B7129CB9D62707AA92C36D3A4675DD37B752D8:\n' +
        'exitcode=33, steps=23, gas_used=0\n' +
        'VM Log (truncated):\n' +
        '...te NOW\n' +
        'execute LEQ\n' +
        'execute THROWIF 36\n' +
        'execute PUSH c4\n' +
        'execute CTOS\n' +
        'execute LDU 32\n' +
        'execute LDU 32\n' +
        'execute LDU 256\n' +
        'execute LDDICT\n' +
        'execute ENDS\n' +
        'execute XCPU s4,s3\n' +
        'execute EQUAL\n' +
        'execute THROWIFNOT 33\n' +
        'default exception handler, terminating vm with exit code 33\n',
      code: 500
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
```
